<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GraphExploring\GraphExploring.csproj"/>
    <ProjectReference Include="..\Library\Library.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
    <PackageReference Include="coverlet.collector" Version="10.0.1"/>
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0"/>
  </ItemGroup>
</Project>